(define (mult-new a b)
    (define (even? b)
	(= (remainder b 2) 0))
    (define (double x) (+ x x))
    (define (halve x)
	    (/ x 2))
    (define (fast-mult-new a b)
	(cond ((= b 0) 0)
	      ((even? b) (double (fast-mult-new a (halve b))))
	      (else (+ a (fast-mult-new a (- b 1))))))
    (fast-mult-new a b))