(define (search-for-primes start end count)
    (define (timed-prime-test n)
	(newline)
        (display n)
	(start-prime-test n (runtime)))
    (define (start-prime-test n start-time)
	(if (prime? n)
	    (report-prime (- (runtime) start-time))
	    0))
    (define (report-prime elapsed-time)
	(display " *** ")
        (display elapsed-time)
	1)
    (define (prime? n)
	(= n (smallest-divisor n)))
    (define (search-iter start end count)
	(if (or (> start end) (= count 0))
	    0
	    (if (= (timed-prime-test start) 1)
		(search-iter (+ start 1) end (- count 1))
		(search-iter (+ start 1) end count))))
    (search-iter start end count))