(define (fix-point f first-guess)
    (define tolerance 0.00001)
    (define (close-enough? v1 v2)
	(< (abs (- v1 v2)) tolerance))
    (define (try guess)
	(newline)
      (display guess)
	(let ((next (f guess)))
	  (if (close-enough? guess next)
	      next
	      (try next))))
    (try first-guess))

(define (xx1000 guess)
    (define (funX x)
	(/ (log 1000) (log x)))
  (fix-point funX guess))
(define (xx1000-avg guess)
    (define (funX x)
	(/ (log 1000) (log x)))
    (define (avg-funX x)
	(/ (+ x (funX x)) 2))
  (fix-point avg-funX guess))
